jobs:
  build:
    docker:
      - image: cimg/base:stable                   # similar to "image" in GitLab
    steps:
      - checkout
      - run: echo "This is a build step"          # similar to "script" in GitLab

  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "This is a test step"
  semgrep:
    docker:
      - image: returntocorp/semgrep-agent:v1
    environment:
      SEMGREP_RULES: >- # more at semgrep.dev/explore
        p/security-audit
        p/secrets
        p/django

    steps:
      - checkout

      - run:
          name: "Semgrep scan"
          command: semgrep-agent --gitlab-json > semgrep-output.json

      - store_artifacts:
          path: semgrep-output.json
          destination: semgrep-artifact
  integration:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: echo "This is a deploy step"

workflows:
  version: 2
  django:
    jobs:
      - build
      - test
      - integration
      - prod:
          type: approval
