name: Django                                  # workflow name

on:
  push:
    branches:                                 # similar to "only" in GitLab
      - main

jobs:
  build:
    runs-on: ubuntu-22.04                    # similar to "image" in GitLab
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        continue-on-error: true
      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py check


  test:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
        continue-on-error: true
      - run: |
          pip3 install --upgrade virtualenv
          virtualenv env
          source env/bin/activate
          pip install -r requirements.txt
          python manage.py test taskManager


  integration:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - run: echo "This is an integration step"
      - run: exit 1
        continue-on-error: true

  prod:
    runs-on: ubuntu-22.04
    needs: integration
    steps:
      - run: echo "This is a deploy step."

  sast:
    env:
           DOJO_HOST: "$DOJO_HOST"
           DOJO_API_TOKEN: "$DOJO_API_TOKEN"
    runs-on: ubuntu-22.04
    needs: build
    continue-on-error: true
    steps:
    - run: |
         docker pull hysnsec/bandit
         docker run --user $(id -u):$(id -g) -v $(pwd):/src --rm hysnsec/bandit -r /src -f json -o /src/bandit-output.json
         curl https://gitlab.practical-devsecops.training/-/snippets/28/raw -o upload-results.py || true
         python3 upload-results.py --host "${{ secrets.DOJO_HOST }}" --api_key "${{ secrets.DOJO_API_TOKEN }}" --engagement_id 1 --product_id 1 --lead_id 1 --environment "Production" --result_file bandit-output.json --scanner "Bandit Scan" 
